declare module '@env' {
  export const API_URL: string;
  export const API_URL_GETALL_PRODUCT: string;
  export const API_URL_LOGIN_USERS: string;
  export const API_URL_REGISTER_USERS: string;
  export const API_PROVINCE: string;
  export const API_DISTRICT: string;
  export const API_COMMUNE: string;
  export const GET_CATORY: string;
  export const GET_CATORY_TYPE: string;
  export const API_GET_ALL_BANNER: string;
  export const API_CREATE_BILL: string;
  export const API_CREATE_BILL_DETAIL: string;
  export const API_URL_VERYFI_OTP: string;
  export const API_URL_GENERATE_OTP: string;
  export const API_GET_BILL_USER: string;
  export const API_GET_BILL_DETAIL_USER: string;
  export const GET_PRODUCT_BY_ID_OBJECT: string;
  export const GET_PRODUCT_BY_ID: string;
}
